### ISSUE TITLE
Clicking Name in friendlist doesn't toggle the information to close

### ISSUE THREAD

**Issue by Pokom** [ChrisMondok/get-together#15]
Open up friends list, toggle a friends name to open up the information on the user's marker. This might be a new feature request, but I would expect when clicking the name again, it would close the information on the user instead of having to find the x and click it.

**Comment by Pokom** [comment]
I think we can make this closed. WIth it merged it's working as I'd expect.

**Comment by ChrisMondok** [comment]
I thought I did that last night...
