### ISSUE TITLE
If a user is offline when a friend leaves, their ghost sticks around forever

### ISSUE THREAD

**Issue by ChrisMondok** [ChrisMondok/get-together#5]

**Comment by Pokom** [comment]
Do you think this will be solved with this #12?

**Comment by ChrisMondok** [comment]
Partially. Once #12 is merged, I'm going to do a slight tweak to how handling getting a list of users works. Basically, I'm going to remove friends where the friend isn't found in that message, and update all others.

**Comment by ChrisMondok** [comment]
Fixed in 60dd888 (client/FriendsList.js:53)
