### ISSUE TITLE
How to share

### ISSUE THREAD

**Issue by Pokom** [ChrisMondok/get-together#7]
I do not see an obvious way of sharing other then copy pasta'ing the URL to someone. Will add a share button.

**Comment by ChrisMondok** [comment]
I was planning on redoing the friends menu, to do something like this:

![image](https://cloud.githubusercontent.com/assets/779770/15321496/c927dca2-1c04-11e6-9069-cfebe5407821.png)

So don't go nuts on the FriendsList, it's going away.

As an aside, the circles are intended to be colors. They might go away, but we're not gaining avatars.

**Comment by ChrisMondok** [comment]
I meant to close this a while ago. There's a share link in the bottom right corner of the friends list now.
